FROM node:22.10-bookworm-slim AS base

RUN apt-get update && apt-get install -y \
    bash \
    net-tools\
    openssl \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*


ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /dir


RUN npm install -g --arch=x64 --platform=linux --libc=glibc sharp@0.33.0-rc.2
RUN npm install --force @img/sharp-linux-x64

RUN yarn global add node-gyp
RUN yarn install --frozen-lockfile
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app
COPY prisma ./prisma/
COPY .env ./

EXPOSE 3000